name: 'UnitSauce'
description: 'AI-powered CLI that diagnoses failing pytest tests, generates minimal fixes with confidence scoring, and posts them directly on your PR.'
author: 'Zan Starasinic'

branding:
  icon: 'check-circle'
  color: 'orange'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key'
    required: true
  github_token:
    description: 'GitHub token for posting PR comments'
    required: true
  mode:
    description: 'Fix mode: auto, code, test'
    required: false
    default: 'auto'
  debug:
    description: 'Enable debug output'
    required: false
    default: 'false'

outputs:
  result:
    description: 'JSON result of fix attempts'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install UnitSauce
      shell: bash
      run: |
        pip install ${{ github.action_path }}
    
    - name: Run UnitSauce
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        DEBUG: ${{ inputs.debug }}
      run: |
        unitsauce . --mode ${{ inputs.mode }} --output markdown >> $GITHUB_STEP_SUMMARY